### ISSUE TITLE
error at running in windows

### ISSUE THREAD

**Issue by eseunghwan** [codelv/declaracad#12]
I have an trouble with running cad.

target pc spec is
OS: Windows 10
Python: python 3.6(x32)
Installed dependencies: Yes(of course, c/p install manual)

but some error occurs like below....
![image](https://user-images.githubusercontent.com/22045289/44263140-c3c3a200-a258-11e8-8d6a-88846fdc4f56.png)

is it python version mismatch?

**Comment by frmdstryr** [comment]
Can you copy and paste the output?

**Comment by eseunghwan** [comment]
output here.


`
Windows fatal exception: access violation

Current thread 0x000015a4 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 922 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 658 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "D:\Software\Anaconda3\lib\site-packages\qtpy\__init__.py", line 122 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "D:\Software\Anaconda3\lib\site-packages\enaml\qt\__init__.py", line 8 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 941 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "D:\Software\Anaconda3\lib\site-packages\enamlx\qt\qt_factories.py", line 8 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "D:\Software\Anaconda3\lib\site-packages\enamlx\__init__.py", line 3 in install
  File "D:\Downloads\declaracad-master\declaracad\apps\workbench.py", line 18 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 678 in exec_module
  File "<frozen importlib._bootstrap>", line 665 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 955 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 971 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1023 in _handle_fromlist
  File "D:\Downloads\declaracad-master\declaracad\__init__.py", line 26 in launch_workbench
  File "D:\Downloads\declaracad-master\declaracad\__init__.py", line 47 in main
  File "main.py", line 16 in <module>
`

**Comment by frmdstryr** [comment]
It looks like a problem with Qt. Which version of PyQt is installed?

Can you try to import PyQt5 from a python console and see if there are any errors?

**Comment by eseunghwan** [comment]
```
PS D:\Downloads\declaracad-master> python3
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:23:52) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtWidgets, QtGui
>>>
```

successfully imported PyQt5


And something new happens
```
PS D:\Downloads\declaracad-master> python3 .\main.py
Traceback (most recent call last):
  File ".\main.py", line 16, in <module>
    main()
  File "D:\Downloads\declaracad-master\declaracad\__init__.py", line 47, in main
    launcher(args)
  File "D:\Downloads\declaracad-master\declaracad\__init__.py", line 26, in launch_workbench
    from declaracad.apps import workbench
  File "D:\Downloads\declaracad-master\declaracad\apps\workbench.py", line 39, in <module>
    from enaml.qt import QtWebEngineWidgets
  File "D:\Software\Anaconda3\lib\site-packages\enaml\qt\QtWebEngineWidgets.py", line 8, in <module>
    from qtpy.QtWebEngineWidgets import *
  File "D:\Software\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name
```

**Comment by frmdstryr** [comment]
Interesting. Does this import work from the python terminal?

```python
from PyQt5.QtWebEngineWidgets import QWebEnginePage
```

As a workaround you should be able to change the `except ImportError:` to `except:` in this line https://github.com/codelv/declaracad/blob/master/declaracad/apps/workbench.py#L40

**Comment by frmdstryr** [comment]
You can also try to make sure PyQt5 is up to date with `pip install --upgrade PyQt5`

**Comment by frmdstryr** [comment]
Please reopen if the problem persists. Thanks.
