### ISSUE TITLE
Declaracad crash

### ISSUE THREAD

**Issue by ceremcem** [codelv/declaracad#16]
Hi, 

I opened the `bottle` example, closed Declaracad, reopened it and it opens the last opened file (the `bottle` example), then closed the window with code editor's `x` button: 

![image](https://user-images.githubusercontent.com/6639874/52155248-ddd03000-2692-11e9-83d9-c148013fc2b5.png)

...and then Declaracad crashed. Here is the traceback: 

```
2019-02-02 02:25:58,431 | DEBUG   | declaracad | Closing '/home/ceremcem/declaracad/examples/bottle.enaml'
2019-02-02 02:25:58,435 | INFO    | declaracad | Saving state due to change: {'type': 'container', 'name': 'documents', 'object': <declaracad.editor.plugin.EditorPlugin object at 0x7f693c433688>, 'value': [<declaracad.editor.plugin.Document object at 0x7f693c19b148>], 'operation': 'remove', 'item': <declaracad.editor.plugin.Document object at 0x7f693c19bd48>}
2019-02-02 02:25:58,437 | INFO    | declaracad | Saving state due to change: {'type': 'update', 'object': <declaracad.editor.plugin.EditorPlugin object at 0x7f693c433688>, 'name': 'active_document', 'oldvalue': <declaracad.editor.plugin.Document object at 0x7f693c19bd48>, 'value': <declaracad.editor.plugin.Document object at 0x7f693c19b148>}
2019-02-02 02:26:02,343 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[]"}
2019-02-02 02:26:03,280 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[]"}
2019-02-02 02:26:05,789 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[<declaracad.occ.algo.ThickSolid object at 0x7f4cc65bc288>]"}
2019-02-02 02:26:06,452 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[]"}
2019-02-02 02:26:21,328 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[<declaracad.occ.algo.ThickSolid object at 0x7f4cc65bc288>]"}
2019-02-02 02:26:22,274 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[<declaracad.occ.algo.ThickSolid object at 0x7f4cc65bc288>]"}
2019-02-02 02:26:23,158 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[<declaracad.occ.algo.ThickSolid object at 0x7f4cc65bc288>]"}
2019-02-02 02:26:27,898 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[<declaracad.occ.algo.ThickSolid object at 0x7f4cc65bc288>]"}
2019-02-02 02:26:30,331 | DEBUG   | declaracad | renderer | sent | {'jsonrpc': '2.0', 'method': 'ping', 'params': {}, 'id': 'keep_alive'}
2019-02-02 02:26:30,334 | DEBUG   | declaracad | render | out | {"id": "keep_alive", "jsonrpc": "2.0", "result": true}
2019-02-02 02:26:31,553 | DEBUG   | declaracad | render | out | {"id": "shape_selection", "jsonrpc": "2.0", "result": "[<declaracad.occ.algo.ThickSolid object at 0x7f4cc65bc288>]"}
2019-02-02 02:26:37,042 | INFO    | declaracad | Saving state due to change: {'type': 'update', 'object': <declaracad.editor.plugin.EditorPlugin object at 0x7f693c433688>, 'name': 'active_document', 'oldvalue': <declaracad.editor.plugin.Document object at 0x7f693c19b148>, 'value': <declaracad.editor.plugin.Document object at 0x7f69180f65c8>}
2019-02-02 02:26:37,830 | DEBUG   | declaracad | Closing ''
2019-02-02 02:26:37,846 | INFO    | declaracad | Saving state due to change: {'type': 'container', 'name': 'documents', 'object': <declaracad.editor.plugin.EditorPlugin object at 0x7f693c433688>, 'value': [], 'operation': 'remove', 'item': <declaracad.editor.plugin.Document object at 0x7f693c19b148>}
2019-02-02 02:26:37,855 | INFO    | declaracad | Detected syntax: 
2019-02-02 02:26:37,857 | DEBUG   | declaracad | Loading '' from disk.
Traceback (most recent call last):
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/qt/qt_dock_item.py", line 178, in on_closed
    d._item_closed()
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/widgets/dock_item.py", line 159, in _item_closed
    self.closed()
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/declarative_meta.py", line 68, in declarative_change_handler
    engine.write(owner, change['name'], change)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/expression_engine.py", line 217, in write
    pair.writer(owner, name, change)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/core/standard_handlers.py", line 82, in __call__
    call_func(func, (), {}, scope)
  File "/home/ceremcem/declaracad/declaracad/editor/view.enaml", line 531, in f
    {'document':doc, 'target': view.name})
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/core/core_plugin.py", line 78, in invoke_command
    return command.handler(event)
  File "/home/ceremcem/declaracad/declaracad/editor/manifest.enaml", line 103, in close_editor
    plugin.close_file(doc.name)
  File "/home/ceremcem/declaracad/declaracad/editor/plugin.py", line 318, in close_file
    self.documents = self._default_documents()
  File "/home/ceremcem/declaracad/declaracad/editor/plugin.py", line 222, in _update_area_layout
    area.update_layout(op)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/widgets/dock_area.py", line 171, in update_layout
    self.proxy.update_layout(ops)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/qt/qt_dock_area.py", line 281, in update_layout
    self.manager.update_layout(ops)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/qt/docking/dock_manager.py", line 198, in update_layout
    builder(op)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/nodevisitor.py", line 34, in __call__
    self.visit(node)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/nodevisitor.py", line 101, in visit
    visitor(node)
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/qt/docking/layout_builder.py", line 506, in visit_InsertTab
    bar_position = area.dockBarPosition(target)
AttributeError: 'NoneType' object has no attribute 'dockBarPosition'
Fatal Python error: Aborted

Thread 0x00007f690bfff700 (most recent call first):
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/selectors.py", line 445 in select
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/asyncio/base_events.py", line 1398 in _run_once
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/asyncio/base_events.py", line 422 in run_forever
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132 in start
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/ipykernel/iostream.py", line 78 in _thread_main
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 864 in run
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f6919afa700 (most recent call first):
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 295 in wait
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 551 in wait
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/IPython/core/history.py", line 829 in run
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/IPython/core/history.py", line 58 in needs_sqlite
  File "<decorator-gen-24>", line 2 in run
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f691c1f6700 (most recent call first):
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/jedi/evaluate/compiled/subprocess/__init__.py", line 38 in _enqueue_output
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 864 in run
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007f696d400740 (most recent call first):
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/qt/qt_application.py", line 48 in start
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/ui/ui_plugin.py", line 105 in start_application
  File "/home/ceremcem/.miniconda2/envs/declaracad/lib/python3.6/site-packages/enaml/workbench/ui/ui_workbench.py", line 42 in run
  File "/home/ceremcem/declaracad/declaracad/apps/workbench.py", line 59 in main
  File "/home/ceremcem/declaracad/declaracad/__init__.py", line 27 in launch_workbench
  File "/home/ceremcem/declaracad/declaracad/__init__.py", line 47 in main
  File "main.py", line 16 in <module>
Aborted
```

# Version 

```
git rev-parse --verify HEAD
54729a79bf0b0977d98907b5afc40473e92f691d
```

**Comment by frmdstryr** [comment]
Thanks, will have a look.

**Comment by zjw1120** [comment]
hi 
   How to Realize LinearForm? No relevant examples were found.

**Comment by zjw1120** [comment]
TypeError: could not resolve a toolkit implementation for the 'LinearForm' component when running under a 'QtApplication'

**Comment by frmdstryr** [comment]
@zjw1120 that was not yet implemented, please create a separate issue.

**Comment by frmdstryr** [comment]
Still not sure of the root cause here but a workaround was added in bf23a6d
