### ISSUE TITLE
Renderer isn't rendering

### ISSUE THREAD

**Issue by DeadlyDad** [codelv/declaracad#25]
Thanks to a lot of hard work on the part of y'all, DeclaraCAD now opens in WIndows (after I install 'git' & 'service_identity').  Unfortunately, while everything else seems to work, there is no output in the viewer windows.  I've attached the console output which is a result of opening DC up with the bottle example from the last session, then pressing <F2> to run the script.  If I let it run, it will keep looping the same six lines forever.  Any ideas?

[errorlog.txt](https://github.com/codelv/declaracad/files/4396507/errorlog.txt)

**Comment by frmdstryr** [comment]
Try running `declaracad view examples/draw.enaml` that should give the actual error.

**Comment by DeadlyDad** [comment]
Here is what I get:
```
(declaracad37) C:\Users\spamt\declaracad>declaracad view examples/draw.enaml
Traceback (most recent call last):
  File "c:\users\spamt\declaracad\declaracad\occ\qt\qt_occ_viewer.py", line 181, in paintEvent
    self.proxy.init_window()
  File "c:\users\spamt\declaracad\declaracad\occ\qt\qt_occ_viewer.py", line 408, in init_window
    window = WNT_Window(win_id)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int)
    2. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor)
    3. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor, theParent: capsule)
    4. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor, theParent: capsule, theMenu: capsule)
    5. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor, theParent: capsule, theMenu: capsule, theClientStruct: capsule)
    6. OCCT.WNT.WNT_Window(aHandle: capsule)
    7. OCCT.WNT.WNT_Window(aHandle: capsule, aBackColor: OCCT.Quantity.Quantity_NameOfColor)

Invoked with: <sip.voidptr object at 0x00000297260FB918>
```

**Comment by frmdstryr** [comment]
Can you pull and see if https://github.com/codelv/declaracad/commit/43f5e2d730c67f1b5aeb07d6b5b224138d24d0bb fixed it?

**Comment by DeadlyDad** [comment]
```
(declaracad37) C:\Users\spamt\declaracad>git pull
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 65 (delta 36), reused 44 (delta 26), pack-reused 0
Unpacking objects: 100% (65/65), done.
From https://github.com/codelv/declaracad
   1956fdf..c3a5690  master     -> origin/master
Updating 1956fdf..c3a5690
Fast-forward
 declaracad/occ/draw.py               |  36 ++++++-
 declaracad/occ/impl/occ_algo.py      |  11 +-
 declaracad/occ/impl/occ_dimension.py |  34 +++---
 declaracad/occ/impl/occ_draw.py      |  31 ++++--
 declaracad/occ/impl/occ_shape.py     |  29 ++++--
 declaracad/occ/plugin.py             |   2 +
 declaracad/occ/qt/qt_occ_viewer.py   |  41 ++++++--
 declaracad/occ/shape.py              |  61 +++++++++--
 declaracad/occ/view.enaml            | 196 ++++++++++++++++++++++++++++-------
 declaracad/occ/widgets/occ_viewer.py |  14 +++
 examples/bolt.enaml                  |  71 ++++++++-----
 examples/bottle.enaml                |  52 ++++++----
 12 files changed, 437 insertions(+), 141 deletions(-)

(declaracad37) C:\Users\spamt\declaracad>declaracad view examples/draw.enaml
Traceback (most recent call last):
  File "c:\users\spamt\declaracad\declaracad\occ\qt\qt_occ_viewer.py", line 178, in paintEvent
    self.proxy.init_window()
  File "c:\users\spamt\declaracad\declaracad\occ\qt\qt_occ_viewer.py", line 405, in init_window
    window = WNT_Window(win_id)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int)
    2. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor)
    3. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor, theParent: capsule)
    4. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor, theParent: capsule, theMenu: capsule)
    5. OCCT.WNT.WNT_Window(theTitle: str, theClass: OCCT.WNT.WNT_WClass, theStyle: int, thePxLeft: int, thePxTop: int, thePxWidth: int, thePxHeight: int, theBackColor: OCCT.Quantity.Quantity_NameOfColor, theParent: capsule, theMenu: capsule, theClientStruct: capsule)
    6. OCCT.WNT.WNT_Window(aHandle: capsule)
    7. OCCT.WNT.WNT_Window(aHandle: capsule, aBackColor: OCCT.Quantity.Quantity_NameOfColor)

Invoked with: <sip.voidptr object at 0x000001F4FFE911E8>
```

**Comment by frmdstryr** [comment]
Ok, sorry, based on https://github.com/LaughlinResearch/pyOCCT/blob/master/OCCT/Visualization/Basic.py I made another attempt at fixing this in https://github.com/codelv/declaracad/commit/57f8be657daa8bbdd1414db21c2b393a6fd79488 can you update and try that?

I'm working on getting my windows VM back up and running so hopefully I can test it locally...

**Comment by DeadlyDad** [comment]
**SUCCESS!!!!!**
```
(declaracad37) C:\Users\spamt\declaracad>git pull
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 18 (delta 15), reused 15 (delta 12), pack-reused 0
Unpacking objects: 100% (18/18), done.
From https://github.com/codelv/declaracad
   c3a5690..6cbaf81  master     -> origin/master
Updating c3a5690..6cbaf81
Fast-forward
 declaracad/occ/impl/occ_draw.py    | 24 +++---------------------
 declaracad/occ/impl/occ_shape.py   | 25 ++++++++++++++++++++++++-
 declaracad/occ/plugin.py           | 10 ++++++----
 declaracad/occ/qt/qt_occ_viewer.py | 26 ++++++++++++++++++++------
 4 files changed, 53 insertions(+), 32 deletions(-)

(declaracad37) C:\Users\spamt\declaracad>declaracad view examples/draw.enaml
2020-03-29 09:25:13,348 | DEBUG   | declaracad | Rendering...
2020-03-29 09:25:13,354 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF91F10> (0.0%)
2020-03-29 09:25:13,364 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF91FB8> (12.5%)
2020-03-29 09:25:13,366 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF980A0> (25.0%)
2020-03-29 09:25:13,367 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF98490> (37.5%)
2020-03-29 09:25:13,368 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF98688> (50.0%)
2020-03-29 09:25:13,370 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF98570> (62.5%)
2020-03-29 09:25:13,374 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF98880> (75.0%)
2020-03-29 09:25:13,375 | DEBUG   | declaracad | Displaying <OCCT.TopoDS.TopoDS_Wire object at 0x000001484DF98DC0> (87.5%)
2020-03-29 09:25:13,377 | DEBUG   | declaracad | Adding 0 dimensions...
2020-03-29 09:25:13,412 | DEBUG   | declaracad | Took: 0:00:00.083537
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
{"id": "window_id", "jsonrpc": "2.0", "result": 198040}
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
TKOpenGl.WinSystem | Type: Error | ID: 6 | Severity: High | Message:
  wglMakeCurrent() has failed. The handle is invalid.
```

**Comment by DeadlyDad** [comment]
There are still problems with some .enaml files, though:
```
(declaracad37) C:\Users\spamt\declaracad>declaracad view examples/dahlgren300z.enaml
Enaml:421: SyntaxWarning: redeclaration of identifier 'body' (this will be an error in Enaml version 1.0)
Traceback (most recent call last):
  File "examples/dahlgren300z.enaml", line 83, in LinearRail
    attr rotation = []
  File "C:\Users\spamt\miniconda3\envs\declaracad37\lib\site-packages\enaml\core\compiler_helpers.py", line 146, in add_storage
    raise TypeError(msg % (klass.__name__, name))
TypeError: can't override final member 'LinearRail.rotation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\spamt\declaracad\declaracad\occ\view.enaml", line 457, in load_source
    result = load_model(filename, source)
  File "c:\users\spamt\declaracad\declaracad\occ\plugin.py", line 82, in load_model
    exec_(code, namespace)
  File "examples/dahlgren300z.enaml", line 12, in
    def angle2d(p1, p2, i=0, j=1):
  File "examples/dahlgren300z.enaml", line 77, in LinearRail
    enamldef LinearRail(Transform): rail:
  File "examples/dahlgren300z.enaml", line 83, in LinearRail
    attr rotation = []
TypeError
2020-03-29 09:32:14,475 | DEBUG   | declaracad | Rendering...
2020-03-29 09:32:14,476 | DEBUG   | declaracad | No shapes to display
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
{"id": "window_id", "jsonrpc": "2.0", "result": 918904}
TKOpenGl.WinSystem | Type: Error | ID: 6 | Severity: High | Message:
  wglMakeCurrent() has failed. The handle is invalid.
```
(It doesn't render anything.)

**Comment by frmdstryr** [comment]
Oh I need to update that example... I just added a `rotation` attribute yesterday because the direction alone doesn't allow rotation so that's conflicting with that attribute name. 

In general this project has a lot of bugs (as you can tell) as things are changing as I learn...

**Comment by DeadlyDad** [comment]
Meh. No need to apologize.  Rome wasn't rendered in a day.
