### ISSUE TITLE
test on windows 10 failed

### ISSUE THREAD

**Issue by carlkl** [codelv/declaracad#38]
Using miniconda with python-3.7 on Windows 10 and installation of declaracad (git master) in its own environment (also python-3.7) I'm experiencing the following ERROR: `Could not get the viewer to start after several attempts`

full console:
```
2020-07-01 13:19:28,807 | INFO    | declaracad | Workbench starting
2020-07-01 13:19:29,342 | DEBUG   | declaracad | Starting plugin 'declaracad.ui'
c:\\miniconda\envs\declaracad\lib\site-packages\atom\scalars.py:227: FutureWarning: Unicode is deprecated and will be removed in atom 0.6.0
  warnings.warn(FutureWarning(msg))
2020-07-01 13:19:29,404 | DEBUG   | declaracad | Starting plugin 'declaracad.docs'
2020-07-01 13:19:30,065 | DEBUG   | declaracad | Starting plugin 'declaracad.viewer'
2020-07-01 13:19:30,238 | DEBUG   | declaracad | Starting plugin 'declaracad.console'
2020-07-01 13:19:30,807 | DEBUG   | declaracad | Starting plugin 'declaracad.editor'
2020-07-01 13:19:30,807 | DEBUG   | declaracad | Updating dock items: [<declaracad.docs.view.DocsDockItem object at 0x000002012BD27688>, <declaracad.occ.view.ViewerDockItem object at 0x000002012C014A08>, <declaracad.toolbox.view.ToolboxDockItem object at 0x000002012BF643C8>, <declaracad.console.view.ConsoleDockItem object at 0x000002012BD50C88>, <declaracad.cnc.view.ComChannelDockItem object at 0x000002012BEC1F08>, <declaracad.editor.view.EditorDockItem object at 0x000002012C67F408>, <declaracad.editor.view.ErrorsDockItem object at 0x000002012C67F448>, <declaracad.editor.view.OutputDockItem object at 0x000002012C67F3C8>, <declaracad.editor.view.OutlineDockItem object at 0x000002012C67F848>]
2020-07-01 13:19:30,807 | DEBUG   | declaracad | Updating settings pages: [<declaracad.ui.extensions.SettingsPage object at 0x000002012AA99308>, <declaracad.ui.extensions.SettingsPage object at 0x000002012AA99048>, <declaracad.ui.extensions.SettingsPage object at 0x000002012AA8B948>, <declaracad.ui.extensions.SettingsPage object at 0x000002012AA99108>]
Creating new area
2020-07-01 13:19:32,589 | DEBUG   | declaracad | Loading '' from disk.
2020-07-01 13:19:33,026 | DEBUG   | asyncio | Using selector: SelectSelector
2020-07-01 13:19:33,065 | DEBUG   | asyncio | Using selector: SelectSelector
2020-07-01 13:19:33,094 | INFO    | declaracad | Detected syntax:
2020-07-01 13:19:33,096 | DEBUG   | declaracad | Loading '' from disk.
2020-07-01 13:19:33,375 | DEBUG   | declaracad | [<enaml.layout.dock_layout.RemoveItem object at 0x000002012CA58788>]
2020-07-01 13:19:33,380 | DEBUG   | declaracad | Editor added={<declaracad.editor.plugin.Document object at 0x000002012CA6D708>} removed={<declaracad.editor.plugin.Document object at 0x000002014056E048>} targets=set()
2020-07-01 13:19:33,384 | INFO    | declaracad | Detected syntax:
2020-07-01 13:19:33,578 | WARNING | declaracad | renderer | stdout closed
2020-07-01 13:19:33,579 | DEBUG   | declaracad | render | err | c:\\miniconda\envs\declaracad\python.exe: can't open file 'main.py': [Errno 2] No such file or directory
2020-07-01 13:19:33,581 | WARNING | declaracad | renderer | stderr closed
2020-07-01 13:19:33,582 | WARNING | declaracad | renderer | stdio closed (we probably did it)
2020-07-01 13:19:33,582 | WARNING | declaracad | renderer | process ended: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 2.
]
2020-07-01 13:19:33,688 | WARNING | declaracad | renderer | stdout closed
2020-07-01 13:19:33,688 | DEBUG   | declaracad | render | err | c:\\miniconda\envs\declaracad\python.exe: can't open file 'main.py': [Errno 2] No such file or directory
2020-07-01 13:19:33,689 | WARNING | declaracad | renderer | stderr closed
2020-07-01 13:19:33,690 | WARNING | declaracad | renderer | stdio closed (we probably did it)
2020-07-01 13:19:33,690 | WARNING | declaracad | renderer | process ended: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 2.
]
2020-07-01 13:19:33,811 | WARNING | declaracad | renderer | stdout closed
2020-07-01 13:19:33,812 | DEBUG   | declaracad | render | err | c:\\miniconda\envs\declaracad\python.exe: can't open file 'main.py': [Errno 2] No such file or directory
2020-07-01 13:19:33,816 | WARNING | declaracad | renderer | stderr closed
2020-07-01 13:19:33,816 | WARNING | declaracad | renderer | stdio closed (we probably did it)
2020-07-01 13:19:33,817 | WARNING | declaracad | renderer | process ended: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 2.
]
....
2020-07-01 13:19:35,595 | WARNING | declaracad | renderer | stdout closed
2020-07-01 13:19:35,596 | DEBUG   | declaracad | render | err | c:\\miniconda\envs\declaracad\python.exe: can't open file 'main.py': [Errno 2] No such file or directory
2020-07-01 13:19:35,601 | WARNING | declaracad | renderer | stderr closed
2020-07-01 13:19:35,601 | WARNING | declaracad | renderer | stdio closed (we probably did it)
2020-07-01 13:19:35,601 | WARNING | declaracad | renderer | process ended: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 2.
]
2020-07-01 13:19:35,708 | WARNING | declaracad | renderer | stdout closed
2020-07-01 13:19:35,708 | DEBUG   | declaracad | render | err | c:\\miniconda\envs\declaracad\python.exe: can't open file 'main.py': [Errno 2] No such file or directory
2020-07-01 13:19:35,713 | WARNING | declaracad | renderer | stderr closed
2020-07-01 13:19:35,714 | WARNING | declaracad | renderer | stdio closed (we probably did it)
2020-07-01 13:19:35,714 | WARNING | declaracad | renderer | process ended: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ProcessTerminated'>: A process has ended with a probable error condition: process ended with exit code 2.
]
Unhandled Error
Traceback (most recent call last):
  File "c:\\miniconda\envs\declaracad\lib\site-packages\enaml\workbench\ui\ui_plugin.py", line 105, in start_application
    self._application.start()
  File "c:\\miniconda\envs\declaracad\lib\site-packages\enaml\qt\qt_application.py", line 48, in start
    app.exec_()
  File "c:\\miniconda\envs\declaracad\lib\site-packages\qreactor.py", line 277, in iterate_qt
    self.iterate(delay=delay, fromqt=True)
  File "c:\\miniconda\envs\declaracad\lib\site-packages\qreactor.py", line 364, in iterate
    self.runUntilCurrent()
--- <exception caught here> ---
  File "c:\\miniconda\envs\declaracad\lib\site-packages\twisted\internet\base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "c:\\miniconda\envs\declaracad\lib\site-packages\twisted\internet\_pollingfile.py", line 81, in _pollEvent
    workUnits += resource.checkWork()
  File "c:\\miniconda\envs\declaracad\lib\site-packages\twisted\internet\_pollingfile.py", line 137, in checkWork
    self.cleanup()
  File "c:\\miniconda\envs\declaracad\lib\site-packages\twisted\internet\_pollingfile.py", line 142, in cleanup
    self.lostCallback()
  File "c:\\miniconda\envs\declaracad\lib\site-packages\twisted\internet\_dumbwin32proc.py", line 378, in outConnectionLost
    self.proto.childConnectionLost(1)
  File "c:\\miniconda\envs\declaracad\lib\site-packages\twisted\internet\protocol.py", line 661, in childConnectionLost
    self.outConnectionLost()
  File "c:\\miniconda\envs\declaracad\lib\site-packages\declaracad\occ\plugin.py", line 340, in outConnectionLost
    self.restart()
  File "c:\\miniconda\envs\declaracad\lib\site-packages\declaracad\occ\plugin.py", line 234, in restart
    "renderer | Failed to successfully start renderer aborting!")
builtins.RuntimeError: renderer | Failed to successfully start renderer aborting!
```

after windows close

```
2020-07-01 13:43:29,838 | INFO    | declaracad | Saving: C:\Users\user/.config/declaracad/declaracad.editor.json due to {'type': 'update', 'object': <declaracad.editor.plugin.EditorPlugin object at 0x0000027C43A8B448>, 'name': 'last_path', 'oldvalue': 'C:\\Users\\user\\home/', 'value': ''}
2020-07-01 13:43:30,823 | INFO    | declaracad | Workbench stopped
```
> conda list
```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
atom                      0.5.1                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
automat                   20.2.0                   pypi_0    pypi
babel                     2.8.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
boost-cpp                 1.73.0               h2ba7cf6_1    conda-forge
bytecode                  0.11.0                   pypi_0    pypi
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
constantly                15.1.0                   pypi_0    pypi
cryptography              2.9.2                    pypi_0    pypi
curl                      7.71.0               h4b64cdc_0    conda-forge
declaracad                0.4.0.dev0               pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
enaml                     0.11.2                   pypi_0    pypi
enamlx                    0.4.2                    pypi_0    pypi
expat                     2.2.9                he025d50_2    conda-forge
ezdxf                     0.12.5                   pypi_0    pypi
fontconfig                2.13.1            hdcb13c4_1002    conda-forge
freeimage                 3.18.0               h33f27b4_0    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_ha405e13_100    conda-forge
hyperlink                 19.0.0                   pypi_0    pypi
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
incremental               17.5.0                   pypi_0    pypi
ipykernel                 5.3.0                    pypi_0    pypi
ipython                   7.16.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.1                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jpeg                      9d                   he774522_0    conda-forge
jsoncpp                   1.8.4             h1ad3211_1002    conda-forge
jsonpickle                1.4.1                    pypi_0    pypi
jupyter-client            6.1.5                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
krb5                      1.17.1               hc04afaa_1    conda-forge
libcurl                   7.71.0               h4b64cdc_0    conda-forge
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_104    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libssh2                   1.9.0                h3235a2c_2    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libxml2                   2.9.10               h5d81f1c_1    conda-forge
lxml                      4.5.1                    pypi_0    pypi
lz4-c                     1.9.2                h62dcd97_1    conda-forge
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
netgen4smesh              6.2.1804             he980bc4_0    trelau
numpydoc                  1.0.0                    pypi_0    pypi
occt                      7.4.0                h823b557_6    conda-forge
openssl                   1.1.1g               he774522_0    conda-forge
packaging                 20.4                     pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.1.1                   py37_1
ply                       3.11                     pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pyhamcrest                2.0.2                    pypi_0    pypi
pyocct                    7.4.0.0          py37he980bc4_1    trelau
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.0                   pypi_0    pypi
pyqt5-sip                 12.8.0                   pypi_0    pypi
pyqtwebengine             5.15.0                   pypi_0    pypi
pyserial                  3.4                      pypi_0    pypi
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                   pypi_0    pypi
pywin32                   228                      pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
qscintilla                2.11.5                   pypi_0    pypi
qt-reactor                0.6                      pypi_0    pypi
qtconsole                 4.7.5                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
service-identity          18.1.0                   pypi_0    pypi
setuptools                47.3.1                   py37_0
six                       1.15.0                   pypi_0    pypi
smesh4pyocct              8.3.0.4              ha925a31_0    trelau
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    3.1.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.32.3               h2a8f88b_0
tbb                       2020.1               he980bc4_0    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
tornado                   6.0.4                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
twisted                   20.3.0                   pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_2
vtk                       8.2.0           py37h359a0f6_218    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.34.2                   py37_0
wincertstore              0.2                      py37_0
xz                        5.2.5                h2fa13f4_0    conda-forge
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4
zope-interface            5.1.0                    pypi_0    pypi
zstd                      1.4.4                h9f78265_3    conda-forge
```

**Comment by frmdstryr** [comment]
Thanks for the report!  It sounds like the errors from the viewer process is not being caught. 

Can you try to run the viewer directly using `declaracad view examples/fillets.enaml`?  It should show another error message which may help.

**Comment by carlkl** [comment]
Great, this works. Again the messages on the console:

```
(declaracad) C:\Users\user\home>declaracad view declaracad\examples\fillets.enaml

TKOpenGl | Type: Error | ID: 0 | Severity: High | Message:
  Error! OpenGL context reports version 4.6 but does not export required functions for 4.5 (glGetnCompressedTexImage)
Please report this issue to OpenGL driver vendor 'intel'
2020-07-01 15:20:08,815 | INFO    | declaracad | OpenGL version: 4.4
2020-07-01 15:20:08,830 | INFO    | declaracad | GPU memory: 0
2020-07-01 15:20:08,830 | INFO    | declaracad | GPU memory info:
2020-07-01 15:20:08,830 | INFO    | declaracad | Max MSAA samples: 16
2020-07-01 15:20:08,830 | INFO    | declaracad | Supports ray tracing: True
2020-07-01 15:20:08,830 | INFO    | declaracad | Supports textures: True
2020-07-01 15:20:08,830 | INFO    | declaracad | Supports adaptive sampling: True
2020-07-01 15:20:08,830 | INFO    | declaracad | Supports adaptive sampling atomic: False
2020-07-01 15:20:08,939 | DEBUG   | declaracad | Rendering...
2020-07-01 15:20:08,939 | DEBUG   | declaracad | No shapes to display
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
{"jsonrpc": "2.0", "result": 1246166, "id": "window_id"}
{"jsonrpc": "2.0", "id": "render_success"}
{"jsonrpc": "2.0", "id": "capture_output", "result": ""}
2020-07-01 15:20:10,304 | DEBUG   | declaracad | Rendering...
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
2020-07-01 15:20:10,877 | DEBUG   | declaracad | Adding 0 dimensions...
2020-07-01 15:20:11,231 | DEBUG   | declaracad | Took: 0:00:00.927150
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
{"jsonrpc": "2.0", "result": "{<declaracad.occ.algo.Fillet object at 0x000002320EF16608>: {'shapes': {0: <OCCT.TopoDS.TopoDS_Shape object at 0x00000232106249F0>}}}", "id": "shape_selection"}
TKOpenGl.WinSystem | Type: Error | ID: 6 | Severity: High | Message:
  wglMakeCurrent() has failed. Das Handle ist ung³ltig.
```

**Comment by frmdstryr** [comment]
Ok, I think this should be fixed now if you pull the latest changes. It was not using an absolute path when starting the viewer. I changed it so it should work when run from anywhere.

**Comment by carlkl** [comment]
Now it works. Many Thanks!
