### ISSUE TITLE
Error exporting to STL

### ISSUE THREAD

**Issue by tompaton** [codelv/declaracad#40]
Exporting to STL generates an error:

![image](https://user-images.githubusercontent.com/530437/86463233-74b18800-bd70-11ea-92f0-ddae46d51ee2.png)

```
Exporting /home/tom/dev/cad/bridge2.enaml to /home/tom/dev/cad/bridge2.stl...
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    main()
  File "/home/tom/declaracad/declaracad/__init__.py", line 105, in main
    launcher(args)
  File "/home/tom/declaracad/declaracad/__init__.py", line 67, in launch_exporter
    exporter.main(**args.__dict__)
  File "/home/tom/declaracad/declaracad/apps/exporter.py", line 41, in main
    exporter.export()
  File "/home/tom/declaracad/declaracad/occ/exporters/stl/exporter.py", line 67, in export
    exporter.SetASCIIMode(not self.binary)
AttributeError: 'OCCT.StlAPI.StlAPI_Writer' object has no attribute 'SetASCIIMode'
```

Currently running from `af4ce6f` on ubuntu 20.04/miniconda etc.

**Comment by frmdstryr** [comment]
Ok well I disabled that option for now.  Looks like another breaking change after moving to 7.4. (a useless breaking change at that).

**Comment by tompaton** [comment]
Cool, that's fixed the export for me, thanks!
