### ISSUE TITLE
ImportError: DLL load failed while importing win32event:

### ISSUE THREAD

**Issue by johrch** [codelv/declaracad#44]
Hi. I got this error when I tried to run declaracad:

(declaracad) C:\Users\DEMO>declaracad
2020-08-19 10:51:47,519 | INFO    | declaracad | Workbench starting
Traceback (most recent call last):
  File "C:\local\Anaconda3\envs\declaracad\Scripts\declaracad-script.py", line 33, in <module>
   sys.exit(load_entry_point('declaracad', 'console_scripts', 'declaracad')())
  File "c:\users\demo\declaracad\declaracad\__init__.py", line 105, in main
    launcher(args)
  File "c:\users\demo\declaracad\declaracad\__init__.py", line 82, in launch_workbench
    workbench.main(**args.__dict__)
  File "c:\users\demo\declaracad\declaracad\apps\workbench.py", line 68, in main
    workbench.run()
  File "C:\local\Anaconda3\envs\declaracad\lib\site-packages\enaml\workbench\ui\ui_workbench.py", line 40, in run
    ui = self.get_plugin(UI_PLUGIN)
  File "C:\local\Anaconda3\envs\declaracad\lib\site-packages\enaml\workbench\workbench.py", line 151, in get_plugin
    plugin.start()
  File "C:\local\Anaconda3\envs\declaracad\lib\site-packages\enaml\workbench\ui\ui_plugin.py", line 56, in start
    self._create_application()
  File "C:\local\Anaconda3\envs\declaracad\lib\site-packages\enaml\workbench\ui\ui_plugin.py", line 208, in _create_application
    application = extension.factory()
  File "c:\users\demo\declaracad\declaracad\core\manifest.enaml", line 24, in application_factory
    import qreactor
  File "C:\local\Anaconda3\envs\declaracad\lib\site-packages\qreactor.py", line 384, in <module>
    from win32event import CreateEvent, MsgWaitForMultipleObjects
ImportError: DLL load failed while importing win32event: The specified module could not be found.

**Comment by frmdstryr** [comment]
As mentioned in the email downgrading pywin32 seems to work `pip install pywin32==225`.

For the other error, can you pull the latest changes `git pull origin master` and see if it works.

**Comment by johrch** [comment]
Its working now.
Thank you very much.
