### ISSUE TITLE
"no Qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by ceremcem** [codelv/declaracad#48]
I run into the following issue when I run `declaracad`: 

```
declaracad 
2020-12-07 14:11:30,431 | INFO    | asyncqt | Forcing use of PyQt5 as Qt Implementation
2020-12-07 14:11:30,432 | INFO    | asyncqt | Using Qt Implementation: PyQt5
2020-12-07 14:11:30,570 | INFO    | declaracad | Workbench starting
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Fatal Python error: Aborted

Current thread 0x00007efecb792740 (most recent call first):
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/qt/qt_application.py", line 35 in __init__
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/core/app.py", line 32 in __init__
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/core/manifest.enaml", line 23 in application_factory
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_plugin.py", line 208 in _create_application
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_plugin.py", line 56 in start
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/workbench.py", line 151 in get_plugin
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_workbench.py", line 40 in run
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/apps/workbench.py", line 68 in main
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/__init__.py", line 82 in launch_workbench
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/__init__.py", line 105 in main
  File "/home/ceremcem/.miniconda3/envs/declaracad/bin/declaracad", line 33 in <module>
Aborted
```

I have built an application with Pyside2 and it was giving the same error (after freshly installing the OS, Debian Buster). I solved it by https://askubuntu.com/a/839335/371730. However I have no idea how to apply it to the virtual environment.

**Comment by frmdstryr** [comment]
On Wayland you need to set the platform to xcb.

Use `export QT_QPA_PLATFORM=xcb` then run declaracad

**Comment by ceremcem** [comment]
I tried all options in the error message. Here is the result of `xcb`:

```
(declaracad) ceremcem@erik3:~$ export QT_QPA_PLATFORM=xcb 
(declaracad) ceremcem@erik3:~$ declaracad
2020-12-07 19:04:16,620 | INFO    | asyncqt | Forcing use of PyQt5 as Qt Implementation
2020-12-07 19:04:16,620 | INFO    | asyncqt | Using Qt Implementation: PyQt5
2020-12-07 19:04:16,745 | INFO    | declaracad | Workbench starting
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Fatal Python error: Aborted

Current thread 0x00007f4a4e813740 (most recent call first):
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/qt/qt_application.py", line 35 in __init__
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/core/app.py", line 32 in __init__
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/core/manifest.enaml", line 23 in application_factory
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_plugin.py", line 208 in _create_application
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_plugin.py", line 56 in start
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/workbench.py", line 151 in get_plugin
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_workbench.py", line 40 in run
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/apps/workbench.py", line 68 in main
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/__init__.py", line 82 in launch_workbench
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/__init__.py", line 105 in main
  File "/home/ceremcem/.miniconda3/envs/declaracad/bin/declaracad", line 33 in <module>
Aborted
```

Most promising one was `minimal`: 

```
(declaracad) ceremcem@erik3:~$ export QT_QPA_PLATFORM=minimal
(declaracad) ceremcem@erik3:~$ declaracad
2020-12-07 19:06:34,661 | INFO    | asyncqt | Forcing use of PyQt5 as Qt Implementation
2020-12-07 19:06:34,661 | INFO    | asyncqt | Using Qt Implementation: PyQt5
2020-12-07 19:06:34,797 | INFO    | declaracad | Workbench starting
2020-12-07 19:06:34,832 | DEBUG   | asyncio | Using selector: _Selector
2020-12-07 19:06:34,849 | DEBUG   | declaracad | Starting plugin 'declaracad.ui'
2020-12-07 19:06:34,869 | DEBUG   | declaracad | Starting plugin 'declaracad.docs'
2020-12-07 19:06:34,875 | DEBUG   | declaracad | Starting plugin 'declaracad.console'
2020-12-07 19:06:35,264 | DEBUG   | declaracad | Starting plugin 'declaracad.viewer'
Traceback (most recent call last):
  File "/home/ceremcem/.miniconda3/envs/declaracad/bin/declaracad", line 33, in <module>
    sys.exit(load_entry_point('declaracad', 'console_scripts', 'declaracad')())
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/__init__.py", line 105, in main
    launcher(args)
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/__init__.py", line 82, in launch_workbench
    workbench.main(**args.__dict__)
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/apps/workbench.py", line 68, in main
    workbench.run()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_workbench.py", line 40, in run
    ui = self.get_plugin(UI_PLUGIN)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/workbench.py", line 151, in get_plugin
    plugin.start()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_plugin.py", line 60, in start
    self._start_autostarts()
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/ui/ui_plugin.py", line 397, in _start_autostarts
    workbench.get_plugin(autostart.plugin_id)
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/workbench/workbench.py", line 151, in get_plugin
    plugin.start()
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/ui/plugin.py", line 48, in start
    self._refresh_dock_items()
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/ui/plugin.py", line 122, in _refresh_dock_items
    DockItem = declaration.factory()
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/cnc/manifest.enaml", line 36, in com_channel_factory
    from .view import ComChannelDockItem
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/ceremcem/.miniconda3/envs/declaracad/lib/python3.8/site-packages/enaml/core/import_hooks.py", line 159, in exec_module
    exec(code, module.__dict__)
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/cnc/view.enaml", line 24, in 
    from .plugin import CncPlugin, Device
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/cnc/plugin.py", line 24, in <module>
    from declaracad.core.serial import SerialTransport, create_serial_connection
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/core/serial.py", line 49, in <module>
    patch_pyserial_if_needed()
  File "/home/ceremcem/.miniconda3/envs/declaracad/declaracad/declaracad/core/serial.py", line 40, in patch_pyserial_if_needed
    dummy = ListPortInfo()
TypeError: __init__() missing 1 required positional argument: 'device'
```

However, none of them worked.

**Comment by frmdstryr** [comment]
Wow pyserial finally did an update after 3 years. I'll remove that hack...
