### ISSUE TITLE
Settings menu does not work

### ISSUE THREAD

**Issue by VictorLamoine** [codelv/declaracad#7]
When clicking an item in this menu, the GUI freezes, please ask if you need more debug info:
```
Saving dock area
Traceback (most recent call last):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/qt/q_deferred_caller.py", line 42, in customEvent
    event.callback(*event.args, **event.kwargs)
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/workbench/ui/workbench_menus.enaml", line 24, in invoke_action
    core.invoke_command(item.command, item.parameters, item)
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/workbench/core/core_plugin.py", line 78, in invoke_command
    return command.handler(event)
  File "/home/victor/libraries/declaracad/declaracad/ui/manifest.enaml", line 40, in open_preferences
    from declaracad.ui.dialogs import PreferencesDialog
ModuleNotFoundError: No module named 'declaracad.ui.dialogs'
Fatal Python error: Aborted

Thread 0x00007f64791e3700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/utils/garbage.py", line 47 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f64799e4700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/sugar/poll.py", line 99 in poll
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 122 in poll
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/tornado/ioloop.py", line 863 in start
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177 in start
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/ipykernel/iostream.py", line 78 in _thread_main
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 864 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f647b267700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 295 in wait
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 551 in wait
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/IPython/core/history.py", line 829 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/IPython/core/history.py", line 58 in needs_sqlite
  File "<decorator-gen-24>", line 2 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007f64e6a40700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/qt/qt_application.py", line 48 in start
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/workbench/ui/ui_plugin.py", line 105 in start_application
  File "/home/victor/libraries/declaracad/declaracad/core/workbench.py", line 113 in run
  File "main.py", line 40 in <module>
```

```
Saving dock area
Traceback (most recent call last):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/qt/q_deferred_caller.py", line 42, in customEvent
    event.callback(*event.args, **event.kwargs)
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/workbench/ui/workbench_menus.enaml", line 24, in invoke_action
    core.invoke_command(item.command, item.parameters, item)
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/workbench/core/core_plugin.py", line 78, in invoke_command
    return command.handler(event)
  File "/home/victor/libraries/declaracad/declaracad/editor/manifest.enaml", line 76, in open_settings
    from .views.api import SettingsDialog
ModuleNotFoundError: No module named 'declaracad.editor.views'
Fatal Python error: Aborted

Thread 0x00007ff9467fc700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/utils/garbage.py", line 47 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff946ffd700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/sugar/poll.py", line 99 in poll
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 122 in poll
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/tornado/ioloop.py", line 863 in start
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177 in start
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/ipykernel/iostream.py", line 78 in _thread_main
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 864 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff94cc67700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 295 in wait
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 551 in wait
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/IPython/core/history.py", line 829 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/IPython/core/history.py", line 58 in needs_sqlite
  File "<decorator-gen-24>", line 2 in run
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/opt/anaconda3/envs/occ/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007ff9b8444700 (most recent call first):
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/qt/qt_application.py", line 48 in start
  File "/opt/anaconda3/envs/occ/lib/python3.6/site-packages/enaml/workbench/ui/ui_plugin.py", line 105 in start_application
  File "/home/victor/libraries/declaracad/declaracad/core/workbench.py", line 113 in run
  File "main.py", line 40 in <module>
Abandon (core dumped)

```

**Comment by frmdstryr** [comment]
Thanks for reporting this, I ported this from another app and it looks like I forgot to move everything. 

Will see if I can move it today.

**Comment by frmdstryr** [comment]
Not very many options yet, but let me know if it's still giving the error. Thanks!

**Comment by VictorLamoine** [comment]
Works now!
